[2022-08-30 20:40:55 +0530] [527054] [INFO] Starting gunicorn 20.1.0
[2022-08-30 20:40:55 +0530] [527054] [INFO] Listening at: http://0.0.0.0:5080 (527054)
[2022-08-30 20:40:55 +0530] [527054] [INFO] Using worker: sync
[2022-08-30 20:40:55 +0530] [527055] [INFO] Booting worker with pid: 527055
[2022-09-06 23:09:04 +0530] [527054] [INFO] Handling signal: term
[2022-09-06 23:09:05 +0530] [527055] [INFO] Worker exiting (pid: 527055)
[2022-09-06 23:09:09 +0530] [527054] [INFO] Shutting down: Master
[2022-09-08 11:25:59 +0530] [1592] [INFO] Starting gunicorn 20.1.0
[2022-09-08 11:25:59 +0530] [1592] [INFO] Listening at: http://0.0.0.0:5080 (1592)
[2022-09-08 11:25:59 +0530] [1592] [INFO] Using worker: sync
[2022-09-08 11:25:59 +0530] [1684] [INFO] Booting worker with pid: 1684
[2022-09-08 11:26:29 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:1684)
[2022-09-08 11:26:29 +0530] [1684] [INFO] Worker exiting (pid: 1684)
[2022-09-08 11:26:30 +0530] [2099] [INFO] Booting worker with pid: 2099
[2022-09-08 11:27:00 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:2099)
[2022-09-08 11:27:00 +0530] [2099] [INFO] Worker exiting (pid: 2099)
[2022-09-08 11:27:00 +0530] [2812] [INFO] Booting worker with pid: 2812
[2022-09-08 11:27:30 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:2812)
[2022-09-08 11:27:30 +0530] [2812] [INFO] Worker exiting (pid: 2812)
[2022-09-08 11:27:30 +0530] [3868] [INFO] Booting worker with pid: 3868
[2022-09-08 11:28:01 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:3868)
[2022-09-08 11:28:01 +0530] [3868] [INFO] Worker exiting (pid: 3868)
[2022-09-08 11:28:01 +0530] [4852] [INFO] Booting worker with pid: 4852
[2022-09-08 11:28:31 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:4852)
[2022-09-08 11:28:31 +0530] [4852] [INFO] Worker exiting (pid: 4852)
[2022-09-08 11:28:31 +0530] [5220] [INFO] Booting worker with pid: 5220
[2022-09-08 11:29:01 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:5220)
[2022-09-08 11:29:01 +0530] [5220] [INFO] Worker exiting (pid: 5220)
[2022-09-08 11:29:02 +0530] [5264] [INFO] Booting worker with pid: 5264
[2022-09-08 11:29:32 +0530] [1592] [CRITICAL] WORKER TIMEOUT (pid:5264)
[2022-09-08 11:29:32 +0530] [5264] [INFO] Worker exiting (pid: 5264)
[2022-09-08 11:29:32 +0530] [5658] [INFO] Booting worker with pid: 5658
[2022-09-08 11:52:19 +0530] [1592] [INFO] Handling signal: term
[2022-09-08 11:52:19 +0530] [5658] [INFO] Worker exiting (pid: 5658)
[2022-09-08 11:52:19 +0530] [1592] [INFO] Shutting down: Master
[2022-09-08 11:52:21 +0530] [24628] [INFO] Starting gunicorn 20.1.0
[2022-09-08 11:52:21 +0530] [24628] [INFO] Listening at: http://0.0.0.0:5080 (24628)
[2022-09-08 11:52:21 +0530] [24628] [INFO] Using worker: sync
[2022-09-08 11:52:21 +0530] [24629] [INFO] Booting worker with pid: 24629
[2022-09-08 11:54:14,915] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 31, in index
    return render_template('index.html',data=data,from_page=from_page,to_page=to_page,current=current,next=next_page,previous=previous_page,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/index.html", line 121, in top-level template code
    {% if not data[x]['metadata'][-1]['website'] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element -5
[2022-09-08 11:54:15,010] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 17, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-08 12:03:38,697] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 31, in index
    return render_template('index.html',data=data,from_page=from_page,to_page=to_page,current=current,next=next_page,previous=previous_page,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/index.html", line 121, in top-level template code
    {% if not data[x]['metadata'][-1]['website'] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element -5
[2022-09-08 12:03:38,838] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 17, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-08 12:06:42 +0530] [24628] [INFO] Handling signal: term
[2022-09-08 12:06:42 +0530] [24629] [INFO] Worker exiting (pid: 24629)
[2022-09-08 12:06:42 +0530] [24628] [INFO] Shutting down: Master
[2022-09-08 12:06:44 +0530] [26848] [INFO] Starting gunicorn 20.1.0
[2022-09-08 12:06:44 +0530] [26848] [INFO] Listening at: http://0.0.0.0:5080 (26848)
[2022-09-08 12:06:44 +0530] [26848] [INFO] Using worker: sync
[2022-09-08 12:06:44 +0530] [26850] [INFO] Booting worker with pid: 26850
[2022-09-08 13:41:44 +0530] [26848] [INFO] Handling signal: term
[2022-09-08 13:41:44 +0530] [26850] [INFO] Worker exiting (pid: 26850)
[2022-09-08 13:41:45 +0530] [26848] [INFO] Shutting down: Master
[2022-09-08 13:41:46 +0530] [45286] [INFO] Starting gunicorn 20.1.0
[2022-09-08 13:41:46 +0530] [45286] [INFO] Listening at: http://0.0.0.0:5080 (45286)
[2022-09-08 13:41:46 +0530] [45286] [INFO] Using worker: sync
[2022-09-08 13:41:46 +0530] [45288] [INFO] Booting worker with pid: 45288
[2022-09-13 16:32:05 +0530] [347174] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:32:05 +0530] [347174] [INFO] Listening at: http://0.0.0.0:5080 (347174)
[2022-09-13 16:32:05 +0530] [347174] [INFO] Using worker: sync
[2022-09-13 16:32:05 +0530] [347175] [INFO] Booting worker with pid: 347175
[2022-09-13 16:32:09,116] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'scholarship_page' did not return a valid response. The function either returned None or ended without a return statement.
[2022-09-13 16:33:52 +0530] [347174] [INFO] Handling signal: term
[2022-09-13 16:33:52 +0530] [347175] [INFO] Worker exiting (pid: 347175)
[2022-09-13 16:33:52 +0530] [347174] [INFO] Shutting down: Master
[2022-09-13 16:33:54 +0530] [347288] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:33:54 +0530] [347288] [INFO] Listening at: http://0.0.0.0:5080 (347288)
[2022-09-13 16:33:54 +0530] [347288] [INFO] Using worker: sync
[2022-09-13 16:33:54 +0530] [347289] [INFO] Booting worker with pid: 347289
[2022-09-13 16:33:58,689] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:34:25,009] ERROR in app: Exception on /view/631989e4254c573c88d5b18b [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:46:03 +0530] [347288] [INFO] Handling signal: term
[2022-09-13 16:46:03 +0530] [347289] [INFO] Worker exiting (pid: 347289)
[2022-09-13 16:46:03 +0530] [347288] [INFO] Shutting down: Master
[2022-09-13 16:46:05 +0530] [348035] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:46:05 +0530] [348035] [INFO] Listening at: http://0.0.0.0:5080 (348035)
[2022-09-13 16:46:05 +0530] [348035] [INFO] Using worker: sync
[2022-09-13 16:46:05 +0530] [348036] [INFO] Booting worker with pid: 348036
[2022-09-13 16:47:13,030] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:47:13,588] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 18, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 16:47:58 +0530] [348035] [INFO] Handling signal: term
[2022-09-13 16:47:58 +0530] [348036] [INFO] Worker exiting (pid: 348036)
[2022-09-13 16:47:58 +0530] [348035] [INFO] Shutting down: Master
[2022-09-13 16:47:59 +0530] [348515] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:47:59 +0530] [348515] [INFO] Listening at: http://0.0.0.0:5080 (348515)
[2022-09-13 16:47:59 +0530] [348515] [INFO] Using worker: sync
[2022-09-13 16:47:59 +0530] [348516] [INFO] Booting worker with pid: 348516
[2022-09-13 16:48:50,651] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:48:59,005] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:49:04,449] ERROR in app: Exception on /view/63198b7750f8c732d010ec8f [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:51:42 +0530] [348515] [INFO] Handling signal: term
[2022-09-13 16:51:42 +0530] [348516] [INFO] Worker exiting (pid: 348516)
[2022-09-13 16:51:43 +0530] [348515] [INFO] Shutting down: Master
[2022-09-13 16:51:44 +0530] [348754] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:51:44 +0530] [348754] [INFO] Listening at: http://0.0.0.0:5080 (348754)
[2022-09-13 16:51:44 +0530] [348754] [INFO] Using worker: sync
[2022-09-13 16:51:44 +0530] [348755] [INFO] Booting worker with pid: 348755
[2022-09-13 16:51:54,661] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return jsonify(scholarship_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:52:07,561] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return jsonify(scholarship_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:53:30 +0530] [348754] [INFO] Handling signal: term
[2022-09-13 16:53:30 +0530] [348755] [INFO] Worker exiting (pid: 348755)
[2022-09-13 16:53:30 +0530] [348754] [INFO] Shutting down: Master
[2022-09-13 16:53:32 +0530] [348837] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:53:32 +0530] [348837] [INFO] Listening at: http://0.0.0.0:5080 (348837)
[2022-09-13 16:53:32 +0530] [348837] [INFO] Using worker: sync
[2022-09-13 16:53:32 +0530] [348838] [INFO] Booting worker with pid: 348838
[2022-09-13 16:53:38,071] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 36, in scholarship_page
    return jsonify(scholarship_data),200
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:53:43 +0530] [348837] [INFO] Handling signal: term
[2022-09-13 16:53:43 +0530] [348838] [INFO] Worker exiting (pid: 348838)
[2022-09-13 16:53:43 +0530] [348837] [INFO] Shutting down: Master
[2022-09-13 16:53:45 +0530] [348883] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:53:45 +0530] [348883] [INFO] Listening at: http://0.0.0.0:5080 (348883)
[2022-09-13 16:53:45 +0530] [348883] [INFO] Using worker: sync
[2022-09-13 16:53:45 +0530] [348884] [INFO] Booting worker with pid: 348884
[2022-09-13 16:54:08 +0530] [348883] [INFO] Handling signal: term
[2022-09-13 16:54:08 +0530] [348884] [INFO] Worker exiting (pid: 348884)
[2022-09-13 16:54:08 +0530] [348883] [INFO] Shutting down: Master
[2022-09-13 16:54:09 +0530] [348910] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:09 +0530] [348910] [INFO] Listening at: http://0.0.0.0:5080 (348910)
[2022-09-13 16:54:09 +0530] [348910] [INFO] Using worker: sync
[2022-09-13 16:54:09 +0530] [348911] [INFO] Booting worker with pid: 348911
[2022-09-13 16:54:11,366] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1723, in make_response
    raise TypeError(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1719, in make_response
    rv = self.response_class.force_type(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 268, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/test.py", line 1237, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: str() argument 2 must be str, not function
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a type.
[2022-09-13 16:54:17,816] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 18, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 16:54:19 +0530] [348910] [INFO] Handling signal: term
[2022-09-13 16:54:19 +0530] [348911] [INFO] Worker exiting (pid: 348911)
[2022-09-13 16:54:20 +0530] [348910] [INFO] Shutting down: Master
[2022-09-13 16:54:21 +0530] [348923] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:21 +0530] [348923] [INFO] Listening at: http://0.0.0.0:5080 (348923)
[2022-09-13 16:54:21 +0530] [348923] [INFO] Using worker: sync
[2022-09-13 16:54:21 +0530] [348924] [INFO] Booting worker with pid: 348924
[2022-09-13 16:54:34 +0530] [348923] [INFO] Handling signal: term
[2022-09-13 16:54:34 +0530] [348924] [INFO] Worker exiting (pid: 348924)
[2022-09-13 16:54:35 +0530] [348923] [INFO] Shutting down: Master
[2022-09-13 16:54:36 +0530] [348942] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:36 +0530] [348942] [INFO] Listening at: http://0.0.0.0:5080 (348942)
[2022-09-13 16:54:36 +0530] [348942] [INFO] Using worker: sync
[2022-09-13 16:54:36 +0530] [348943] [INFO] Booting worker with pid: 348943
[2022-09-13 16:54:38,446] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1723, in make_response
    raise TypeError(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1719, in make_response
    rv = self.response_class.force_type(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 268, in force_type
    response = Response(*run_wsgi_app(response, environ))
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/werkzeug/test.py", line 1237, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: str() argument 2 must be str, not function
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a type.
[2022-09-13 16:54:42 +0530] [348942] [INFO] Handling signal: term
[2022-09-13 16:54:42 +0530] [348943] [INFO] Worker exiting (pid: 348943)
[2022-09-13 16:54:42 +0530] [348942] [INFO] Shutting down: Master
[2022-09-13 16:54:43 +0530] [348986] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:54:43 +0530] [348986] [INFO] Listening at: http://0.0.0.0:5080 (348986)
[2022-09-13 16:54:43 +0530] [348986] [INFO] Using worker: sync
[2022-09-13 16:54:43 +0530] [348987] [INFO] Booting worker with pid: 348987
[2022-09-13 16:55:19 +0530] [348986] [INFO] Handling signal: term
[2022-09-13 16:55:19 +0530] [348987] [INFO] Worker exiting (pid: 348987)
[2022-09-13 16:55:20 +0530] [348986] [INFO] Shutting down: Master
[2022-09-13 16:55:21 +0530] [349029] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:55:21 +0530] [349029] [INFO] Listening at: http://0.0.0.0:5080 (349029)
[2022-09-13 16:55:21 +0530] [349029] [INFO] Using worker: sync
[2022-09-13 16:55:21 +0530] [349030] [INFO] Booting worker with pid: 349030
[2022-09-13 16:56:23 +0530] [349029] [INFO] Handling signal: term
[2022-09-13 16:56:23 +0530] [349030] [INFO] Worker exiting (pid: 349030)
[2022-09-13 16:56:23 +0530] [349029] [INFO] Shutting down: Master
[2022-09-13 16:56:24 +0530] [349097] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:56:24 +0530] [349097] [INFO] Listening at: http://0.0.0.0:5080 (349097)
[2022-09-13 16:56:24 +0530] [349097] [INFO] Using worker: sync
[2022-09-13 16:56:24 +0530] [349098] [INFO] Booting worker with pid: 349098
[2022-09-13 16:58:38 +0530] [349287] [INFO] Starting gunicorn 20.1.0
[2022-09-13 16:58:38 +0530] [349287] [INFO] Listening at: http://0.0.0.0:5080 (349287)
[2022-09-13 16:58:38 +0530] [349287] [INFO] Using worker: sync
[2022-09-13 16:58:38 +0530] [349288] [INFO] Booting worker with pid: 349288
[2022-09-13 16:58:43,906] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 16:58:44,486] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 18, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 17:00:23 +0530] [349413] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:00:23 +0530] [349413] [INFO] Listening at: http://0.0.0.0:5080 (349413)
[2022-09-13 17:00:23 +0530] [349413] [INFO] Using worker: sync
[2022-09-13 17:00:23 +0530] [349414] [INFO] Booting worker with pid: 349414
[2022-09-13 17:00:25,971] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return json.loads(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2022-09-13 17:00:26,583] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 19, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 17:00:42 +0530] [349413] [INFO] Handling signal: term
[2022-09-13 17:00:42 +0530] [349414] [INFO] Worker exiting (pid: 349414)
[2022-09-13 17:00:43 +0530] [349413] [INFO] Shutting down: Master
[2022-09-13 17:00:44 +0530] [349466] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:00:44 +0530] [349466] [INFO] Listening at: http://0.0.0.0:5080 (349466)
[2022-09-13 17:00:44 +0530] [349466] [INFO] Using worker: sync
[2022-09-13 17:00:44 +0530] [349467] [INFO] Booting worker with pid: 349467
[2022-09-13 17:00:46,875] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37, in scholarship_page
    return json.dumps(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:01:31 +0530] [349501] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:31 +0530] [349501] [INFO] Listening at: http://0.0.0.0:5080 (349501)
[2022-09-13 17:01:31 +0530] [349501] [INFO] Using worker: sync
[2022-09-13 17:01:31 +0530] [349502] [INFO] Booting worker with pid: 349502
[2022-09-13 17:01:31 +0530] [349502] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:31 +0530] [349502] [INFO] Worker exiting (pid: 349502)
[2022-09-13 17:01:31 +0530] [349501] [INFO] Shutting down: Master
[2022-09-13 17:01:31 +0530] [349501] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:32 +0530] [349503] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:32 +0530] [349503] [INFO] Listening at: http://0.0.0.0:5080 (349503)
[2022-09-13 17:01:32 +0530] [349503] [INFO] Using worker: sync
[2022-09-13 17:01:32 +0530] [349504] [INFO] Booting worker with pid: 349504
[2022-09-13 17:01:32 +0530] [349504] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:32 +0530] [349504] [INFO] Worker exiting (pid: 349504)
[2022-09-13 17:01:32 +0530] [349503] [INFO] Shutting down: Master
[2022-09-13 17:01:32 +0530] [349503] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:34 +0530] [349505] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:34 +0530] [349505] [INFO] Listening at: http://0.0.0.0:5080 (349505)
[2022-09-13 17:01:34 +0530] [349505] [INFO] Using worker: sync
[2022-09-13 17:01:34 +0530] [349506] [INFO] Booting worker with pid: 349506
[2022-09-13 17:01:34 +0530] [349506] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:34 +0530] [349506] [INFO] Worker exiting (pid: 349506)
[2022-09-13 17:01:34 +0530] [349505] [INFO] Shutting down: Master
[2022-09-13 17:01:34 +0530] [349505] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:37 +0530] [349509] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:37 +0530] [349509] [INFO] Listening at: http://0.0.0.0:5080 (349509)
[2022-09-13 17:01:37 +0530] [349509] [INFO] Using worker: sync
[2022-09-13 17:01:37 +0530] [349512] [INFO] Booting worker with pid: 349512
[2022-09-13 17:01:37 +0530] [349512] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 37
    print scholarship_data
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scholarship_data)?
[2022-09-13 17:01:37 +0530] [349512] [INFO] Worker exiting (pid: 349512)
[2022-09-13 17:01:37 +0530] [349509] [INFO] Shutting down: Master
[2022-09-13 17:01:37 +0530] [349509] [INFO] Reason: Worker failed to boot.
[2022-09-13 17:01:54 +0530] [349554] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:01:54 +0530] [349554] [INFO] Listening at: http://0.0.0.0:5080 (349554)
[2022-09-13 17:01:54 +0530] [349554] [INFO] Using worker: sync
[2022-09-13 17:01:54 +0530] [349555] [INFO] Booting worker with pid: 349555
[2022-09-13 17:02:05,522] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return json.dumps(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:02:28,167] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return json.dumps(scholarship_data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:03:15 +0530] [349554] [INFO] Handling signal: term
[2022-09-13 17:03:15 +0530] [349555] [INFO] Worker exiting (pid: 349555)
[2022-09-13 17:03:15 +0530] [349554] [INFO] Shutting down: Master
[2022-09-13 17:03:16 +0530] [349637] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:03:16 +0530] [349637] [INFO] Listening at: http://0.0.0.0:5080 (349637)
[2022-09-13 17:03:16 +0530] [349637] [INFO] Using worker: sync
[2022-09-13 17:03:16 +0530] [349638] [INFO] Booting worker with pid: 349638
[2022-09-13 17:03:19,508] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return jsonify(scholarship_data)
NameError: name 'jsonify' is not defined
[2022-09-13 17:03:50 +0530] [349637] [INFO] Handling signal: term
[2022-09-13 17:03:50 +0530] [349638] [INFO] Worker exiting (pid: 349638)
[2022-09-13 17:03:50 +0530] [349637] [INFO] Shutting down: Master
[2022-09-13 17:03:51 +0530] [349695] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:03:51 +0530] [349695] [INFO] Listening at: http://0.0.0.0:5080 (349695)
[2022-09-13 17:03:51 +0530] [349695] [INFO] Using worker: sync
[2022-09-13 17:03:51 +0530] [349696] [INFO] Booting worker with pid: 349696
[2022-09-13 17:03:55,893] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 38, in scholarship_page
    return jsonify(scholarship_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2022-09-13 17:06:47 +0530] [349695] [INFO] Handling signal: term
[2022-09-13 17:06:47 +0530] [349696] [INFO] Worker exiting (pid: 349696)
[2022-09-13 17:06:48 +0530] [349695] [INFO] Shutting down: Master
[2022-09-13 17:06:49 +0530] [349890] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:06:49 +0530] [349890] [INFO] Listening at: http://0.0.0.0:5080 (349890)
[2022-09-13 17:06:49 +0530] [349890] [INFO] Using worker: sync
[2022-09-13 17:06:49 +0530] [349891] [INFO] Booting worker with pid: 349891
[2022-09-13 17:07:02,853] ERROR in app: Exception on /view/631989e4254c573c88d5b18c [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 39, in scholarship_page
    return json.loads(json_util.dumps(scholarship_data))
NameError: name 'json_util' is not defined
[2022-09-13 17:08:07 +0530] [349890] [INFO] Handling signal: term
[2022-09-13 17:08:07 +0530] [349891] [INFO] Worker exiting (pid: 349891)
[2022-09-13 17:08:07 +0530] [349890] [INFO] Shutting down: Master
[2022-09-13 17:08:08 +0530] [349974] [INFO] Starting gunicorn 20.1.0
[2022-09-13 17:08:08 +0530] [349974] [INFO] Listening at: http://0.0.0.0:5080 (349974)
[2022-09-13 17:08:08 +0530] [349974] [INFO] Using worker: sync
[2022-09-13 17:08:08 +0530] [349975] [INFO] Booting worker with pid: 349975
[2022-09-13 19:16:12 +0530] [349974] [CRITICAL] WORKER TIMEOUT (pid:349975)
[2022-09-13 19:16:12 +0530] [349975] [INFO] Worker exiting (pid: 349975)
[2022-09-13 19:16:13 +0530] [357416] [INFO] Booting worker with pid: 357416
[2022-09-13 19:20:12 +0530] [349974] [CRITICAL] WORKER TIMEOUT (pid:357416)
[2022-09-13 19:20:12 +0530] [357416] [INFO] Worker exiting (pid: 357416)
[2022-09-13 19:20:12 +0530] [357654] [INFO] Booting worker with pid: 357654
[2022-09-13 23:49:30 +0530] [349974] [INFO] Handling signal: term
[2022-09-13 23:49:30 +0530] [357654] [INFO] Worker exiting (pid: 357654)
[2022-09-13 23:49:31 +0530] [349974] [INFO] Shutting down: Master
[2022-09-13 23:49:32 +0530] [377175] [INFO] Starting gunicorn 20.1.0
[2022-09-13 23:49:32 +0530] [377175] [INFO] Listening at: http://0.0.0.0:5080 (377175)
[2022-09-13 23:49:32 +0530] [377175] [INFO] Using worker: sync
[2022-09-13 23:49:32 +0530] [377176] [INFO] Booting worker with pid: 377176
[2022-09-13 23:49:42,573] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 125, in top-level template code
    {% set url = data[x]['metadata'][-1]['website'] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: dict object has no element Undefined
[2022-09-13 23:49:42,625] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-13 23:51:37 +0530] [377175] [INFO] Handling signal: term
[2022-09-13 23:51:37 +0530] [377176] [INFO] Worker exiting (pid: 377176)
[2022-09-13 23:51:37 +0530] [377175] [INFO] Shutting down: Master
[2022-09-13 23:51:38 +0530] [377393] [INFO] Starting gunicorn 20.1.0
[2022-09-13 23:51:38 +0530] [377393] [INFO] Listening at: http://0.0.0.0:5080 (377393)
[2022-09-13 23:51:38 +0530] [377393] [INFO] Using worker: sync
[2022-09-13 23:51:38 +0530] [377394] [INFO] Booting worker with pid: 377394
[2022-09-13 23:51:44,734] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 155, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 125, in template
    {% set url = data[x]['metadata'][0s]['website'] %}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 's'
[2022-09-13 23:52:01 +0530] [377393] [INFO] Handling signal: term
[2022-09-13 23:52:01 +0530] [377394] [INFO] Worker exiting (pid: 377394)
[2022-09-13 23:52:02 +0530] [377393] [INFO] Shutting down: Master
[2022-09-13 23:52:03 +0530] [377477] [INFO] Starting gunicorn 20.1.0
[2022-09-13 23:52:03 +0530] [377477] [INFO] Listening at: http://0.0.0.0:5080 (377477)
[2022-09-13 23:52:03 +0530] [377477] [INFO] Using worker: sync
[2022-09-13 23:52:03 +0530] [377478] [INFO] Booting worker with pid: 377478
[2022-09-13 23:52:10,550] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 123, in top-level template code
    {% set url = data[x]['url'] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: dict object has no element Undefined
[2022-09-13 23:53:18 +0530] [377477] [INFO] Handling signal: term
[2022-09-13 23:53:18 +0530] [377478] [INFO] Worker exiting (pid: 377478)
[2022-09-13 23:53:19 +0530] [377477] [INFO] Shutting down: Master
[2022-09-13 23:53:20 +0530] [377601] [INFO] Starting gunicorn 20.1.0
[2022-09-13 23:53:20 +0530] [377601] [INFO] Listening at: http://0.0.0.0:5080 (377601)
[2022-09-13 23:53:20 +0530] [377601] [INFO] Using worker: sync
[2022-09-13 23:53:20 +0530] [377602] [INFO] Booting worker with pid: 377602
[2022-09-13 23:58:52 +0530] [377601] [INFO] Handling signal: term
[2022-09-13 23:58:52 +0530] [377602] [INFO] Worker exiting (pid: 377602)
[2022-09-13 23:58:53 +0530] [377601] [INFO] Shutting down: Master
[2022-09-13 23:58:54 +0530] [378654] [INFO] Starting gunicorn 20.1.0
[2022-09-13 23:58:54 +0530] [378654] [INFO] Listening at: http://0.0.0.0:5080 (378654)
[2022-09-13 23:58:54 +0530] [378654] [INFO] Using worker: sync
[2022-09-13 23:58:54 +0530] [378655] [INFO] Booting worker with pid: 378655
[2022-09-13 23:59:19 +0530] [378654] [INFO] Handling signal: term
[2022-09-13 23:59:19 +0530] [378655] [INFO] Worker exiting (pid: 378655)
[2022-09-13 23:59:20 +0530] [378654] [INFO] Shutting down: Master
[2022-09-13 23:59:21 +0530] [378728] [INFO] Starting gunicorn 20.1.0
[2022-09-13 23:59:21 +0530] [378728] [INFO] Listening at: http://0.0.0.0:5080 (378728)
[2022-09-13 23:59:21 +0530] [378728] [INFO] Using worker: sync
[2022-09-13 23:59:21 +0530] [378729] [INFO] Booting worker with pid: 378729
[2022-09-14 00:00:53 +0530] [378728] [INFO] Handling signal: term
[2022-09-14 00:00:53 +0530] [378729] [INFO] Worker exiting (pid: 378729)
[2022-09-14 00:00:53 +0530] [378728] [INFO] Shutting down: Master
[2022-09-14 00:00:55 +0530] [378951] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:00:55 +0530] [378951] [INFO] Listening at: http://0.0.0.0:5080 (378951)
[2022-09-14 00:00:55 +0530] [378951] [INFO] Using worker: sync
[2022-09-14 00:00:55 +0530] [378952] [INFO] Booting worker with pid: 378952
[2022-09-14 00:00:57,974] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 144, in top-level template code
    {% for key,value in data['metadata'].items() %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
[2022-09-14 00:01:00,550] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 144, in top-level template code
    {% for key,value in data['metadata'].items() %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
[2022-09-14 00:01:09 +0530] [378951] [INFO] Handling signal: term
[2022-09-14 00:01:09 +0530] [378952] [INFO] Worker exiting (pid: 378952)
[2022-09-14 00:01:09 +0530] [378951] [INFO] Shutting down: Master
[2022-09-14 00:01:11 +0530] [379011] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:01:11 +0530] [379011] [INFO] Listening at: http://0.0.0.0:5080 (379011)
[2022-09-14 00:01:11 +0530] [379011] [INFO] Using worker: sync
[2022-09-14 00:01:11 +0530] [379012] [INFO] Booting worker with pid: 379012
[2022-09-14 00:01:16,206] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 144, in top-level template code
    {% for key,value in data['metadata'].items() %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
[2022-09-14 00:05:52 +0530] [379011] [INFO] Handling signal: term
[2022-09-14 00:05:52 +0530] [379012] [INFO] Worker exiting (pid: 379012)
[2022-09-14 00:05:52 +0530] [379011] [INFO] Shutting down: Master
[2022-09-14 00:05:54 +0530] [379745] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:05:54 +0530] [379745] [INFO] Listening at: http://0.0.0.0:5080 (379745)
[2022-09-14 00:05:54 +0530] [379745] [INFO] Using worker: sync
[2022-09-14 00:05:54 +0530] [379746] [INFO] Booting worker with pid: 379746
[2022-09-14 00:06:09,971] ERROR in app: Exception on /view/63198b7750f8c732d010ec8f [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 145, in top-level template code
    {% set key = list(data.keys())[0] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'list' is undefined
[2022-09-14 00:06:10,043] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-14 00:06:16,738] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 145, in top-level template code
    {% set key = list(data.keys())[0] %}
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'list' is undefined
[2022-09-14 00:08:02 +0530] [379745] [INFO] Handling signal: term
[2022-09-14 00:08:02 +0530] [379746] [INFO] Worker exiting (pid: 379746)
[2022-09-14 00:08:02 +0530] [379745] [INFO] Shutting down: Master
[2022-09-14 00:08:03 +0530] [380035] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:08:03 +0530] [380035] [INFO] Listening at: http://0.0.0.0:5080 (380035)
[2022-09-14 00:08:03 +0530] [380035] [INFO] Using worker: sync
[2022-09-14 00:08:03 +0530] [380037] [INFO] Booting worker with pid: 380037
[2022-09-14 00:08:43 +0530] [380035] [INFO] Handling signal: term
[2022-09-14 00:08:43 +0530] [380037] [INFO] Worker exiting (pid: 380037)
[2022-09-14 00:08:43 +0530] [380035] [INFO] Shutting down: Master
[2022-09-14 00:08:44 +0530] [380124] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:08:44 +0530] [380124] [INFO] Listening at: http://0.0.0.0:5080 (380124)
[2022-09-14 00:08:44 +0530] [380124] [INFO] Using worker: sync
[2022-09-14 00:08:44 +0530] [380125] [INFO] Booting worker with pid: 380125
[2022-09-14 00:09:27 +0530] [380124] [INFO] Handling signal: term
[2022-09-14 00:09:27 +0530] [380125] [INFO] Worker exiting (pid: 380125)
[2022-09-14 00:09:28 +0530] [380124] [INFO] Shutting down: Master
[2022-09-14 00:09:29 +0530] [380263] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:09:29 +0530] [380263] [INFO] Listening at: http://0.0.0.0:5080 (380263)
[2022-09-14 00:09:29 +0530] [380263] [INFO] Using worker: sync
[2022-09-14 00:09:29 +0530] [380264] [INFO] Booting worker with pid: 380264
[2022-09-14 00:14:43 +0530] [380263] [INFO] Handling signal: term
[2022-09-14 00:14:43 +0530] [380264] [INFO] Worker exiting (pid: 380264)
[2022-09-14 00:14:44 +0530] [380263] [INFO] Shutting down: Master
[2022-09-14 00:14:45 +0530] [380575] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:14:45 +0530] [380575] [INFO] Listening at: http://0.0.0.0:5080 (380575)
[2022-09-14 00:14:45 +0530] [380575] [INFO] Using worker: sync
[2022-09-14 00:14:45 +0530] [380576] [INFO] Booting worker with pid: 380576
[2022-09-14 00:15:23 +0530] [380575] [INFO] Handling signal: term
[2022-09-14 00:15:23 +0530] [380576] [INFO] Worker exiting (pid: 380576)
[2022-09-14 00:15:23 +0530] [380575] [INFO] Shutting down: Master
[2022-09-14 00:15:25 +0530] [380707] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:15:25 +0530] [380707] [INFO] Listening at: http://0.0.0.0:5080 (380707)
[2022-09-14 00:15:25 +0530] [380707] [INFO] Using worker: sync
[2022-09-14 00:15:25 +0530] [380708] [INFO] Booting worker with pid: 380708
[2022-09-14 00:17:18 +0530] [380707] [INFO] Handling signal: term
[2022-09-14 00:17:18 +0530] [380708] [INFO] Worker exiting (pid: 380708)
[2022-09-14 00:17:18 +0530] [380707] [INFO] Shutting down: Master
[2022-09-14 00:17:19 +0530] [380884] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:17:19 +0530] [380884] [INFO] Listening at: http://0.0.0.0:5080 (380884)
[2022-09-14 00:17:19 +0530] [380884] [INFO] Using worker: sync
[2022-09-14 00:17:19 +0530] [380885] [INFO] Booting worker with pid: 380885
[2022-09-14 00:17:29,251] ERROR in app: Exception on /view [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'view'
[2022-09-14 00:17:29,319] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-14 00:18:14 +0530] [380884] [INFO] Handling signal: term
[2022-09-14 00:18:14 +0530] [380885] [INFO] Worker exiting (pid: 380885)
[2022-09-14 00:18:15 +0530] [380884] [INFO] Shutting down: Master
[2022-09-14 00:18:16 +0530] [381005] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:18:16 +0530] [381005] [INFO] Listening at: http://0.0.0.0:5080 (381005)
[2022-09-14 00:18:16 +0530] [381005] [INFO] Using worker: sync
[2022-09-14 00:18:16 +0530] [381006] [INFO] Booting worker with pid: 381006
[2022-09-14 00:21:03 +0530] [381005] [INFO] Handling signal: term
[2022-09-14 00:21:03 +0530] [381006] [INFO] Worker exiting (pid: 381006)
[2022-09-14 00:21:03 +0530] [381005] [INFO] Shutting down: Master
[2022-09-14 00:21:04 +0530] [381206] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:21:04 +0530] [381206] [INFO] Listening at: http://0.0.0.0:5080 (381206)
[2022-09-14 00:21:04 +0530] [381206] [INFO] Using worker: sync
[2022-09-14 00:21:04 +0530] [381207] [INFO] Booting worker with pid: 381207
[2022-09-14 00:21:40 +0530] [381206] [INFO] Handling signal: term
[2022-09-14 00:21:40 +0530] [381207] [INFO] Worker exiting (pid: 381207)
[2022-09-14 00:21:40 +0530] [381206] [INFO] Shutting down: Master
[2022-09-14 00:21:41 +0530] [381303] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:21:41 +0530] [381303] [INFO] Listening at: http://0.0.0.0:5080 (381303)
[2022-09-14 00:21:41 +0530] [381303] [INFO] Using worker: sync
[2022-09-14 00:21:41 +0530] [381304] [INFO] Booting worker with pid: 381304
[2022-09-14 00:22:38 +0530] [381303] [INFO] Handling signal: term
[2022-09-14 00:22:38 +0530] [381304] [INFO] Worker exiting (pid: 381304)
[2022-09-14 00:22:39 +0530] [381303] [INFO] Shutting down: Master
[2022-09-14 00:22:40 +0530] [381397] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:22:40 +0530] [381397] [INFO] Listening at: http://0.0.0.0:5080 (381397)
[2022-09-14 00:22:40 +0530] [381397] [INFO] Using worker: sync
[2022-09-14 00:22:40 +0530] [381398] [INFO] Booting worker with pid: 381398
[2022-09-14 00:25:35 +0530] [381397] [INFO] Handling signal: term
[2022-09-14 00:25:35 +0530] [381398] [INFO] Worker exiting (pid: 381398)
[2022-09-14 00:25:35 +0530] [381397] [INFO] Shutting down: Master
[2022-09-14 00:25:36 +0530] [381747] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:25:36 +0530] [381747] [INFO] Listening at: http://0.0.0.0:5080 (381747)
[2022-09-14 00:25:36 +0530] [381747] [INFO] Using worker: sync
[2022-09-14 00:25:36 +0530] [381748] [INFO] Booting worker with pid: 381748
[2022-09-14 00:57:20 +0530] [381747] [INFO] Handling signal: term
[2022-09-14 00:57:20 +0530] [381748] [INFO] Worker exiting (pid: 381748)
[2022-09-14 00:57:20 +0530] [381747] [INFO] Shutting down: Master
[2022-09-14 00:57:21 +0530] [385243] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:57:21 +0530] [385243] [INFO] Listening at: http://0.0.0.0:5080 (385243)
[2022-09-14 00:57:21 +0530] [385243] [INFO] Using worker: sync
[2022-09-14 00:57:21 +0530] [385244] [INFO] Booting worker with pid: 385244
[2022-09-14 00:58:43 +0530] [385243] [INFO] Handling signal: term
[2022-09-14 00:58:43 +0530] [385244] [INFO] Worker exiting (pid: 385244)
[2022-09-14 00:58:43 +0530] [385243] [INFO] Shutting down: Master
[2022-09-14 00:58:45 +0530] [385421] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:58:45 +0530] [385421] [INFO] Listening at: http://0.0.0.0:5080 (385421)
[2022-09-14 00:58:45 +0530] [385421] [INFO] Using worker: sync
[2022-09-14 00:58:45 +0530] [385422] [INFO] Booting worker with pid: 385422
[2022-09-14 00:58:51,083] ERROR in app: Exception on /view/63198b7750f8c732d010ec90 [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 40, in scholarship_page
    return render_template('blog-single.html',data=scholarship_data,recent_data=recent_data)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/templating.py", line 155, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/templates/blog-single.html", line 175, in template
    <img src="{{ url_for('static',filename='assets/img/blog/author.jpg' }}" class="rounded-circle float-left" alt="">
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
[2022-09-14 00:59:16 +0530] [385421] [INFO] Handling signal: term
[2022-09-14 00:59:16 +0530] [385422] [INFO] Worker exiting (pid: 385422)
[2022-09-14 00:59:16 +0530] [385421] [INFO] Shutting down: Master
[2022-09-14 00:59:17 +0530] [385519] [INFO] Starting gunicorn 20.1.0
[2022-09-14 00:59:17 +0530] [385519] [INFO] Listening at: http://0.0.0.0:5080 (385519)
[2022-09-14 00:59:17 +0530] [385519] [INFO] Using worker: sync
[2022-09-14 00:59:17 +0530] [385520] [INFO] Booting worker with pid: 385520
[2022-09-14 01:04:02 +0530] [385519] [INFO] Handling signal: term
[2022-09-14 01:04:02 +0530] [385520] [INFO] Worker exiting (pid: 385520)
[2022-09-14 01:04:03 +0530] [385519] [INFO] Shutting down: Master
[2022-09-14 01:04:04 +0530] [385999] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:04:04 +0530] [385999] [INFO] Listening at: http://0.0.0.0:5080 (385999)
[2022-09-14 01:04:04 +0530] [385999] [INFO] Using worker: sync
[2022-09-14 01:04:04 +0530] [386000] [INFO] Booting worker with pid: 386000
[2022-09-14 01:05:09 +0530] [385999] [INFO] Handling signal: term
[2022-09-14 01:05:09 +0530] [386000] [INFO] Worker exiting (pid: 386000)
[2022-09-14 01:05:09 +0530] [385999] [INFO] Shutting down: Master
[2022-09-14 01:05:11 +0530] [386136] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:05:11 +0530] [386136] [INFO] Listening at: http://0.0.0.0:5080 (386136)
[2022-09-14 01:05:11 +0530] [386136] [INFO] Using worker: sync
[2022-09-14 01:05:11 +0530] [386137] [INFO] Booting worker with pid: 386137
[2022-09-14 01:06:36 +0530] [386136] [INFO] Handling signal: term
[2022-09-14 01:06:36 +0530] [386137] [INFO] Worker exiting (pid: 386137)
[2022-09-14 01:06:37 +0530] [386136] [INFO] Shutting down: Master
[2022-09-14 01:06:38 +0530] [386302] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:06:38 +0530] [386302] [INFO] Listening at: http://0.0.0.0:5080 (386302)
[2022-09-14 01:06:38 +0530] [386302] [INFO] Using worker: sync
[2022-09-14 01:06:38 +0530] [386303] [INFO] Booting worker with pid: 386303
[2022-09-14 01:11:11 +0530] [386302] [INFO] Handling signal: term
[2022-09-14 01:11:11 +0530] [386303] [INFO] Worker exiting (pid: 386303)
[2022-09-14 01:11:12 +0530] [386302] [INFO] Shutting down: Master
[2022-09-14 01:11:13 +0530] [386840] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:11:13 +0530] [386840] [INFO] Listening at: http://0.0.0.0:5080 (386840)
[2022-09-14 01:11:13 +0530] [386840] [INFO] Using worker: sync
[2022-09-14 01:11:13 +0530] [386841] [INFO] Booting worker with pid: 386841
[2022-09-14 01:11:24,913] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-09-14 01:11:40 +0530] [386840] [INFO] Handling signal: term
[2022-09-14 01:11:40 +0530] [386841] [INFO] Worker exiting (pid: 386841)
[2022-09-14 01:11:40 +0530] [386840] [INFO] Shutting down: Master
[2022-09-14 01:11:41 +0530] [386941] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:11:41 +0530] [386941] [INFO] Listening at: http://0.0.0.0:5080 (386941)
[2022-09-14 01:11:41 +0530] [386941] [INFO] Using worker: sync
[2022-09-14 01:11:41 +0530] [386942] [INFO] Booting worker with pid: 386942
[2022-09-14 01:11:46,028] ERROR in app: Exception on /view/ [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: scholarship_page() got an unexpected keyword argument 'page'
[2022-09-14 01:11:49,176] ERROR in app: Exception on /view/ [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: scholarship_page() got an unexpected keyword argument 'page'
[2022-09-14 01:11:54 +0530] [386941] [INFO] Handling signal: term
[2022-09-14 01:11:54 +0530] [386942] [INFO] Worker exiting (pid: 386942)
[2022-09-14 01:11:54 +0530] [386941] [INFO] Shutting down: Master
[2022-09-14 01:11:56 +0530] [386972] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:11:56 +0530] [386972] [INFO] Listening at: http://0.0.0.0:5080 (386972)
[2022-09-14 01:11:56 +0530] [386972] [INFO] Using worker: sync
[2022-09-14 01:11:56 +0530] [386973] [INFO] Booting worker with pid: 386973
[2022-09-14 01:13:24 +0530] [386972] [INFO] Handling signal: term
[2022-09-14 01:13:24 +0530] [386973] [INFO] Worker exiting (pid: 386973)
[2022-09-14 01:13:25 +0530] [386972] [INFO] Shutting down: Master
[2022-09-14 01:13:26 +0530] [387136] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:13:26 +0530] [387136] [INFO] Listening at: http://0.0.0.0:5080 (387136)
[2022-09-14 01:13:26 +0530] [387136] [INFO] Using worker: sync
[2022-09-14 01:13:26 +0530] [387137] [INFO] Booting worker with pid: 387137
[2022-09-14 01:14:01 +0530] [387136] [INFO] Handling signal: term
[2022-09-14 01:14:01 +0530] [387137] [INFO] Worker exiting (pid: 387137)
[2022-09-14 01:14:02 +0530] [387136] [INFO] Shutting down: Master
[2022-09-14 01:14:03 +0530] [387198] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:14:03 +0530] [387198] [INFO] Listening at: http://0.0.0.0:5080 (387198)
[2022-09-14 01:14:03 +0530] [387198] [INFO] Using worker: sync
[2022-09-14 01:14:03 +0530] [387199] [INFO] Booting worker with pid: 387199
[2022-09-14 01:15:16 +0530] [387198] [INFO] Handling signal: term
[2022-09-14 01:15:16 +0530] [387199] [INFO] Worker exiting (pid: 387199)
[2022-09-14 01:15:16 +0530] [387198] [INFO] Shutting down: Master
[2022-09-14 01:15:17 +0530] [387377] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:15:17 +0530] [387377] [INFO] Listening at: http://0.0.0.0:5080 (387377)
[2022-09-14 01:15:17 +0530] [387377] [INFO] Using worker: sync
[2022-09-14 01:15:17 +0530] [387378] [INFO] Booting worker with pid: 387378
[2022-09-14 01:15:21,143] ERROR in app: Exception on /view/ [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: scholarship_page() got an unexpected keyword argument '<string:index>'
[2022-09-14 01:15:49 +0530] [387377] [INFO] Handling signal: term
[2022-09-14 01:15:49 +0530] [387378] [INFO] Worker exiting (pid: 387378)
[2022-09-14 01:15:49 +0530] [387377] [INFO] Shutting down: Master
[2022-09-14 01:15:50 +0530] [387428] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:15:50 +0530] [387428] [INFO] Listening at: http://0.0.0.0:5080 (387428)
[2022-09-14 01:15:50 +0530] [387428] [INFO] Using worker: sync
[2022-09-14 01:15:50 +0530] [387429] [INFO] Booting worker with pid: 387429
[2022-09-14 01:15:55,202] ERROR in app: Exception on /view/ [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: scholarship_page() got an unexpected keyword argument '<index>'
[2022-09-14 01:16:07 +0530] [387428] [INFO] Handling signal: term
[2022-09-14 01:16:07 +0530] [387429] [INFO] Worker exiting (pid: 387429)
[2022-09-14 01:16:07 +0530] [387428] [INFO] Shutting down: Master
[2022-09-14 01:16:08 +0530] [387466] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:16:08 +0530] [387466] [INFO] Listening at: http://0.0.0.0:5080 (387466)
[2022-09-14 01:16:08 +0530] [387466] [INFO] Using worker: sync
[2022-09-14 01:16:08 +0530] [387467] [INFO] Booting worker with pid: 387467
[2022-09-14 01:16:40 +0530] [387466] [INFO] Handling signal: term
[2022-09-14 01:16:40 +0530] [387467] [INFO] Worker exiting (pid: 387467)
[2022-09-14 01:16:41 +0530] [387466] [INFO] Shutting down: Master
[2022-09-14 01:16:42 +0530] [387558] [INFO] Starting gunicorn 20.1.0
[2022-09-14 01:16:42 +0530] [387558] [INFO] Listening at: http://0.0.0.0:5080 (387558)
[2022-09-14 01:16:42 +0530] [387558] [INFO] Using worker: sync
[2022-09-14 01:16:42 +0530] [387559] [INFO] Booting worker with pid: 387559
[2022-10-08 15:32:12 +0530] [1538759] [INFO] Starting gunicorn 20.1.0
[2022-10-08 15:32:12 +0530] [1538759] [INFO] Listening at: http://0.0.0.0:5080 (1538759)
[2022-10-08 15:32:12 +0530] [1538759] [INFO] Using worker: sync
[2022-10-08 15:32:12 +0530] [1538763] [INFO] Booting worker with pid: 1538763
[2022-10-11 12:39:08 +0530] [1538759] [INFO] Handling signal: term
[2022-10-11 12:39:08 +0530] [1538763] [INFO] Worker exiting (pid: 1538763)
[2022-10-11 12:39:11 +0530] [1538759] [INFO] Shutting down: Master
[2022-10-11 12:39:15 +0530] [1791669] [INFO] Starting gunicorn 20.1.0
[2022-10-11 12:39:15 +0530] [1791669] [INFO] Listening at: http://0.0.0.0:5080 (1791669)
[2022-10-11 12:39:15 +0530] [1791669] [INFO] Using worker: sync
[2022-10-11 12:39:15 +0530] [1791672] [INFO] Booting worker with pid: 1791672
[2022-10-14 10:57:43 +0530] [1791669] [INFO] Handling signal: term
[2022-10-14 10:57:44 +0530] [1791672] [INFO] Worker exiting (pid: 1791672)
[2022-10-14 10:57:52 +0530] [2059414] [INFO] Starting gunicorn 20.1.0
[2022-10-14 10:57:52 +0530] [2059414] [INFO] Listening at: http://0.0.0.0:5080 (2059414)
[2022-10-14 10:57:52 +0530] [2059414] [INFO] Using worker: sync
[2022-10-14 10:57:53 +0530] [2059429] [INFO] Booting worker with pid: 2059429
[2022-10-17 11:24:48 +0530] [2059414] [INFO] Handling signal: term
[2022-10-17 11:24:48 +0530] [2059429] [INFO] Worker exiting (pid: 2059429)
[2022-10-17 11:24:48 +0530] [2059414] [INFO] Shutting down: Master
[2022-10-17 11:24:51 +0530] [2308626] [INFO] Starting gunicorn 20.1.0
[2022-10-17 11:24:51 +0530] [2308626] [INFO] Listening at: http://0.0.0.0:5080 (2308626)
[2022-10-17 11:24:51 +0530] [2308626] [INFO] Using worker: sync
[2022-10-17 11:24:51 +0530] [2308628] [INFO] Booting worker with pid: 2308628
[2022-10-20 09:42:57 +0530] [2308626] [INFO] Handling signal: term
[2022-10-20 09:42:58 +0530] [2308628] [INFO] Worker exiting (pid: 2308628)
[2022-10-20 09:43:10 +0530] [2579438] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:43:10 +0530] [2579438] [INFO] Listening at: http://0.0.0.0:5080 (2579438)
[2022-10-20 09:43:10 +0530] [2579438] [INFO] Using worker: sync
[2022-10-20 09:43:10 +0530] [2579447] [INFO] Booting worker with pid: 2579447
[2022-10-20 09:46:23 +0530] [2579438] [INFO] Handling signal: term
[2022-10-20 09:46:23 +0530] [2579447] [INFO] Worker exiting (pid: 2579447)
[2022-10-20 09:46:23 +0530] [2579438] [INFO] Shutting down: Master
[2022-10-20 09:46:25 +0530] [2579891] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:46:25 +0530] [2579891] [INFO] Listening at: http://0.0.0.0:5080 (2579891)
[2022-10-20 09:46:25 +0530] [2579891] [INFO] Using worker: sync
[2022-10-20 09:46:25 +0530] [2579893] [INFO] Booting worker with pid: 2579893
[2022-10-20 09:48:02 +0530] [2579891] [INFO] Handling signal: term
[2022-10-20 09:48:02 +0530] [2579893] [INFO] Worker exiting (pid: 2579893)
[2022-10-20 09:48:02 +0530] [2579891] [INFO] Shutting down: Master
[2022-10-20 09:48:04 +0530] [2580015] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:48:04 +0530] [2580015] [INFO] Listening at: http://0.0.0.0:5080 (2580015)
[2022-10-20 09:48:04 +0530] [2580015] [INFO] Using worker: sync
[2022-10-20 09:48:04 +0530] [2580017] [INFO] Booting worker with pid: 2580017
[2022-10-20 09:49:08 +0530] [2580015] [INFO] Handling signal: term
[2022-10-20 09:49:08 +0530] [2580017] [INFO] Worker exiting (pid: 2580017)
[2022-10-20 09:49:09 +0530] [2580015] [INFO] Shutting down: Master
[2022-10-20 09:49:10 +0530] [2580163] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:49:10 +0530] [2580163] [INFO] Listening at: http://0.0.0.0:5080 (2580163)
[2022-10-20 09:49:10 +0530] [2580163] [INFO] Using worker: sync
[2022-10-20 09:49:10 +0530] [2580170] [INFO] Booting worker with pid: 2580170
[2022-10-20 09:53:06 +0530] [2580163] [INFO] Handling signal: term
[2022-10-20 09:53:06 +0530] [2580170] [INFO] Worker exiting (pid: 2580170)
[2022-10-20 09:53:06 +0530] [2580163] [INFO] Shutting down: Master
[2022-10-20 09:53:08 +0530] [2580612] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:53:08 +0530] [2580612] [INFO] Listening at: http://0.0.0.0:5080 (2580612)
[2022-10-20 09:53:08 +0530] [2580612] [INFO] Using worker: sync
[2022-10-20 09:53:08 +0530] [2580613] [INFO] Booting worker with pid: 2580613
[2022-10-20 09:55:58 +0530] [2580612] [INFO] Handling signal: term
[2022-10-20 09:55:58 +0530] [2580613] [INFO] Worker exiting (pid: 2580613)
[2022-10-20 09:55:58 +0530] [2580612] [INFO] Shutting down: Master
[2022-10-20 09:55:59 +0530] [2580803] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:55:59 +0530] [2580803] [INFO] Listening at: http://0.0.0.0:5080 (2580803)
[2022-10-20 09:55:59 +0530] [2580803] [INFO] Using worker: sync
[2022-10-20 09:55:59 +0530] [2580804] [INFO] Booting worker with pid: 2580804
[2022-10-20 09:57:53 +0530] [2580803] [INFO] Handling signal: term
[2022-10-20 09:57:53 +0530] [2580804] [INFO] Worker exiting (pid: 2580804)
[2022-10-20 09:57:54 +0530] [2580803] [INFO] Shutting down: Master
[2022-10-20 09:57:55 +0530] [2580969] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:57:55 +0530] [2580969] [INFO] Listening at: http://0.0.0.0:5080 (2580969)
[2022-10-20 09:57:55 +0530] [2580969] [INFO] Using worker: sync
[2022-10-20 09:57:55 +0530] [2580971] [INFO] Booting worker with pid: 2580971
[2022-10-20 09:59:29 +0530] [2580969] [INFO] Handling signal: term
[2022-10-20 09:59:29 +0530] [2580971] [INFO] Worker exiting (pid: 2580971)
[2022-10-20 09:59:29 +0530] [2580969] [INFO] Shutting down: Master
[2022-10-20 09:59:31 +0530] [2581119] [INFO] Starting gunicorn 20.1.0
[2022-10-20 09:59:31 +0530] [2581119] [INFO] Listening at: http://0.0.0.0:5080 (2581119)
[2022-10-20 09:59:31 +0530] [2581119] [INFO] Using worker: sync
[2022-10-20 09:59:31 +0530] [2581120] [INFO] Booting worker with pid: 2581120
[2022-10-24 16:09:59 +0530] [2581119] [INFO] Handling signal: term
[2022-10-24 16:09:59 +0530] [2581120] [INFO] Worker exiting (pid: 2581120)
[2022-10-24 16:09:59 +0530] [2581119] [INFO] Shutting down: Master
[2022-10-24 16:10:01 +0530] [2935186] [INFO] Starting gunicorn 20.1.0
[2022-10-24 16:10:01 +0530] [2935186] [INFO] Listening at: http://0.0.0.0:5080 (2935186)
[2022-10-24 16:10:01 +0530] [2935186] [INFO] Using worker: sync
[2022-10-24 16:10:01 +0530] [2935196] [INFO] Booting worker with pid: 2935196
[2022-10-27 21:23:23 +0530] [2935186] [INFO] Handling signal: term
[2022-10-27 21:23:23 +0530] [2935196] [INFO] Worker exiting (pid: 2935196)
[2022-10-27 21:23:23 +0530] [2935186] [INFO] Shutting down: Master
[2022-10-27 21:23:25 +0530] [3209583] [INFO] Starting gunicorn 20.1.0
[2022-10-27 21:23:25 +0530] [3209583] [INFO] Listening at: http://0.0.0.0:5080 (3209583)
[2022-10-27 21:23:25 +0530] [3209583] [INFO] Using worker: sync
[2022-10-27 21:23:25 +0530] [3209584] [INFO] Booting worker with pid: 3209584
[2022-11-01 12:48:11 +0530] [1594] [INFO] Starting gunicorn 20.1.0
[2022-11-01 12:48:11 +0530] [1594] [INFO] Listening at: http://0.0.0.0:5080 (1594)
[2022-11-01 12:48:11 +0530] [1594] [INFO] Using worker: sync
[2022-11-01 12:48:11 +0530] [1716] [INFO] Booting worker with pid: 1716
[2022-11-01 12:48:41 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:1716)
[2022-11-01 12:48:41 +0530] [1716] [INFO] Worker exiting (pid: 1716)
[2022-11-01 12:48:41 +0530] [1925] [INFO] Booting worker with pid: 1925
[2022-11-01 12:49:11 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:1925)
[2022-11-01 12:49:11 +0530] [1925] [INFO] Worker exiting (pid: 1925)
[2022-11-01 12:49:11 +0530] [2020] [INFO] Booting worker with pid: 2020
[2022-11-01 12:49:41 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:2020)
[2022-11-01 12:49:41 +0530] [2020] [INFO] Worker exiting (pid: 2020)
[2022-11-01 12:49:42 +0530] [2113] [INFO] Booting worker with pid: 2113
[2022-11-01 12:50:12 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:2113)
[2022-11-01 12:50:12 +0530] [2113] [INFO] Worker exiting (pid: 2113)
[2022-11-01 12:50:12 +0530] [2379] [INFO] Booting worker with pid: 2379
[2022-11-01 12:50:42 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:2379)
[2022-11-01 12:50:42 +0530] [2379] [INFO] Worker exiting (pid: 2379)
[2022-11-01 12:50:42 +0530] [2701] [INFO] Booting worker with pid: 2701
[2022-11-01 12:51:12 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:2701)
[2022-11-01 12:51:12 +0530] [2701] [INFO] Worker exiting (pid: 2701)
[2022-11-01 12:51:12 +0530] [3227] [INFO] Booting worker with pid: 3227
[2022-11-01 12:51:42 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:3227)
[2022-11-01 12:51:42 +0530] [3227] [INFO] Worker exiting (pid: 3227)
[2022-11-01 12:51:43 +0530] [3581] [INFO] Booting worker with pid: 3581
[2022-11-01 12:52:13 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:3581)
[2022-11-01 12:52:13 +0530] [3581] [INFO] Worker exiting (pid: 3581)
[2022-11-01 12:52:13 +0530] [3818] [INFO] Booting worker with pid: 3818
[2022-11-01 12:52:43 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:3818)
[2022-11-01 12:52:43 +0530] [3818] [INFO] Worker exiting (pid: 3818)
[2022-11-01 12:52:43 +0530] [4010] [INFO] Booting worker with pid: 4010
[2022-11-01 12:53:13 +0530] [1594] [CRITICAL] WORKER TIMEOUT (pid:4010)
[2022-11-01 12:53:13 +0530] [4010] [INFO] Worker exiting (pid: 4010)
[2022-11-01 12:53:14 +0530] [4653] [INFO] Booting worker with pid: 4653
[2022-11-01 20:38:04 +0530] [1594] [INFO] Handling signal: term
[2022-11-01 20:38:04 +0530] [4653] [INFO] Worker exiting (pid: 4653)
[2022-11-01 20:38:04 +0530] [1594] [INFO] Shutting down: Master
[2022-11-01 20:38:06 +0530] [41680] [INFO] Starting gunicorn 20.1.0
[2022-11-01 20:38:06 +0530] [41680] [INFO] Listening at: http://0.0.0.0:5080 (41680)
[2022-11-01 20:38:06 +0530] [41680] [INFO] Using worker: sync
[2022-11-01 20:38:06 +0530] [41681] [INFO] Booting worker with pid: 41681
[2022-11-06 00:19:39 +0530] [41680] [CRITICAL] WORKER TIMEOUT (pid:41681)
[2022-11-06 00:19:39 +0530] [41681] [INFO] Worker exiting (pid: 41681)
[2022-11-06 00:19:39 +0530] [410599] [INFO] Booting worker with pid: 410599
[2022-11-06 00:26:03 +0530] [41680] [INFO] Handling signal: term
[2022-11-06 00:26:03 +0530] [410599] [INFO] Worker exiting (pid: 410599)
[2022-11-06 00:26:04 +0530] [41680] [INFO] Shutting down: Master
[2022-11-06 00:26:04 +0530] [411226] [INFO] Starting gunicorn 20.1.0
[2022-11-06 00:26:04 +0530] [411226] [INFO] Listening at: http://0.0.0.0:5080 (411226)
[2022-11-06 00:26:04 +0530] [411226] [INFO] Using worker: sync
[2022-11-06 00:26:04 +0530] [411227] [INFO] Booting worker with pid: 411227
[2022-11-06 00:27:02 +0530] [411226] [CRITICAL] WORKER TIMEOUT (pid:411227)
[2022-11-06 00:27:02 +0530] [411227] [INFO] Worker exiting (pid: 411227)
[2022-11-06 00:27:02 +0530] [411319] [INFO] Booting worker with pid: 411319
[2022-11-06 01:20:01 +0530] [411226] [CRITICAL] WORKER TIMEOUT (pid:411319)
[2022-11-06 01:20:01 +0530] [411319] [INFO] Worker exiting (pid: 411319)
[2022-11-06 01:20:01 +0530] [415343] [INFO] Booting worker with pid: 415343
[2022-11-06 01:33:17 +0530] [411226] [CRITICAL] WORKER TIMEOUT (pid:415343)
[2022-11-06 01:33:17 +0530] [415343] [INFO] Worker exiting (pid: 415343)
[2022-11-06 01:33:18 +0530] [416098] [INFO] Booting worker with pid: 416098
[2022-11-06 12:32:20 +0530] [411226] [INFO] Handling signal: term
[2022-11-06 12:32:20 +0530] [416098] [INFO] Worker exiting (pid: 416098)
[2022-11-06 12:32:26 +0530] [411226] [INFO] Shutting down: Master
[2022-11-06 12:32:27 +0530] [474405] [INFO] Starting gunicorn 20.1.0
[2022-11-06 12:32:27 +0530] [474405] [INFO] Listening at: http://0.0.0.0:5080 (474405)
[2022-11-06 12:32:27 +0530] [474405] [INFO] Using worker: sync
[2022-11-06 12:32:27 +0530] [474406] [INFO] Booting worker with pid: 474406
[2022-11-06 12:37:35 +0530] [474405] [INFO] Handling signal: term
[2022-11-06 12:37:35 +0530] [474406] [INFO] Worker exiting (pid: 474406)
[2022-11-06 12:37:35 +0530] [474405] [INFO] Shutting down: Master
[2022-11-06 12:37:36 +0530] [475107] [INFO] Starting gunicorn 20.1.0
[2022-11-06 12:37:36 +0530] [475107] [INFO] Listening at: http://0.0.0.0:5080 (475107)
[2022-11-06 12:37:36 +0530] [475107] [INFO] Using worker: sync
[2022-11-06 12:37:36 +0530] [475114] [INFO] Booting worker with pid: 475114
[2022-11-06 12:38:34 +0530] [475107] [INFO] Handling signal: term
[2022-11-06 12:38:34 +0530] [475114] [INFO] Worker exiting (pid: 475114)
[2022-11-06 12:38:34 +0530] [475107] [INFO] Shutting down: Master
[2022-11-06 12:38:36 +0530] [475262] [INFO] Starting gunicorn 20.1.0
[2022-11-06 12:38:36 +0530] [475262] [INFO] Listening at: http://0.0.0.0:5080 (475262)
[2022-11-06 12:38:36 +0530] [475262] [INFO] Using worker: sync
[2022-11-06 12:38:36 +0530] [475263] [INFO] Booting worker with pid: 475263
[2022-11-06 12:40:00 +0530] [475262] [INFO] Handling signal: term
[2022-11-06 12:40:00 +0530] [475263] [INFO] Worker exiting (pid: 475263)
[2022-11-06 12:40:00 +0530] [475262] [INFO] Shutting down: Master
[2022-11-06 12:40:02 +0530] [475504] [INFO] Starting gunicorn 20.1.0
[2022-11-06 12:40:02 +0530] [475504] [INFO] Listening at: http://0.0.0.0:5080 (475504)
[2022-11-06 12:40:02 +0530] [475504] [INFO] Using worker: sync
[2022-11-06 12:40:02 +0530] [475505] [INFO] Booting worker with pid: 475505
[2022-11-06 12:45:37 +0530] [475504] [INFO] Handling signal: term
[2022-11-06 12:45:37 +0530] [475505] [INFO] Worker exiting (pid: 475505)
[2022-11-06 12:45:38 +0530] [475504] [INFO] Shutting down: Master
[2022-11-06 12:45:39 +0530] [476024] [INFO] Starting gunicorn 20.1.0
[2022-11-06 12:45:39 +0530] [476024] [INFO] Listening at: http://0.0.0.0:5080 (476024)
[2022-11-06 12:45:39 +0530] [476024] [INFO] Using worker: sync
[2022-11-06 12:45:39 +0530] [476031] [INFO] Booting worker with pid: 476031
[2022-11-06 13:14:59 +0530] [476024] [INFO] Handling signal: term
[2022-11-06 13:14:59 +0530] [476031] [INFO] Worker exiting (pid: 476031)
[2022-11-06 13:15:00 +0530] [476024] [INFO] Shutting down: Master
[2022-11-06 13:15:01 +0530] [480131] [INFO] Starting gunicorn 20.1.0
[2022-11-06 13:15:01 +0530] [480131] [INFO] Listening at: http://0.0.0.0:5080 (480131)
[2022-11-06 13:15:01 +0530] [480131] [INFO] Using worker: sync
[2022-11-06 13:15:01 +0530] [480133] [INFO] Booting worker with pid: 480133
[2022-11-06 22:36:48 +0530] [480131] [INFO] Handling signal: term
[2022-11-06 22:36:48 +0530] [480133] [INFO] Worker exiting (pid: 480133)
[2022-11-06 22:36:48 +0530] [480131] [INFO] Shutting down: Master
[2022-11-06 22:36:49 +0530] [515127] [INFO] Starting gunicorn 20.1.0
[2022-11-06 22:36:49 +0530] [515127] [INFO] Listening at: http://0.0.0.0:5080 (515127)
[2022-11-06 22:36:49 +0530] [515127] [INFO] Using worker: sync
[2022-11-06 22:36:49 +0530] [515129] [INFO] Booting worker with pid: 515129
[2022-11-06 22:41:05 +0530] [515127] [INFO] Handling signal: term
[2022-11-06 22:41:05 +0530] [515129] [INFO] Worker exiting (pid: 515129)
[2022-11-06 22:41:06 +0530] [515127] [INFO] Shutting down: Master
[2022-11-06 22:41:07 +0530] [515493] [INFO] Starting gunicorn 20.1.0
[2022-11-06 22:41:07 +0530] [515493] [INFO] Listening at: http://0.0.0.0:5080 (515493)
[2022-11-06 22:41:07 +0530] [515493] [INFO] Using worker: sync
[2022-11-06 22:41:07 +0530] [515503] [INFO] Booting worker with pid: 515503
[2022-11-09 18:22:47,019] ERROR in app: Exception on /sitemap.xml [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'sitemap.xml'
[2022-11-09 18:22:47,633] ERROR in app: Exception on /robots.txt [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'robots.txt'
[2022-11-12 10:50:19,540] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'favicon.ico'
[2022-11-13 08:09:54,400] ERROR in app: Exception on /sitemap.xml [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'sitemap.xml'
[2022-11-13 08:09:54,402] ERROR in app: Exception on /robots.txt [GET]
Traceback (most recent call last):
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nacool/Desktop/Projects/scholarship_scraper/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nacool/Desktop/Projects/scholarship_scraper/test_app.py", line 20, in index
    current = int(page)
ValueError: invalid literal for int() with base 10: 'robots.txt'
[2023-01-07 12:11:46 +0530] [374390] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:11:46 +0530] [374390] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:46 +0530] [374390] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:47 +0530] [374390] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:47 +0530] [374390] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:48 +0530] [374390] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:48 +0530] [374390] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:49 +0530] [374390] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:49 +0530] [374390] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:50 +0530] [374390] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:50 +0530] [374390] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:51 +0530] [374390] [ERROR] Can't connect to ('0.0.0.0', 5080)
[2023-01-07 12:11:53 +0530] [374467] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:11:53 +0530] [374467] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:53 +0530] [374467] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:54 +0530] [374467] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:54 +0530] [374467] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:55 +0530] [374467] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:55 +0530] [374467] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:56 +0530] [374467] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:56 +0530] [374467] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:57 +0530] [374467] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:11:57 +0530] [374467] [ERROR] Retrying in 1 second.
[2023-01-07 12:11:58 +0530] [374467] [ERROR] Can't connect to ('0.0.0.0', 5080)
[2023-01-07 12:11:59 +0530] [374519] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:11:59 +0530] [374519] [INFO] Listening at: http://0.0.0.0:5080 (374519)
[2023-01-07 12:11:59 +0530] [374519] [INFO] Using worker: sync
[2023-01-07 12:11:59 +0530] [374524] [INFO] Booting worker with pid: 374524
[2023-01-07 12:12:21 +0530] [374559] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:12:21 +0530] [374559] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:21 +0530] [374559] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:22 +0530] [374559] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:22 +0530] [374559] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:23 +0530] [374559] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:23 +0530] [374559] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:24 +0530] [374559] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:24 +0530] [374559] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:25 +0530] [374559] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:25 +0530] [374559] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:26 +0530] [374559] [ERROR] Can't connect to ('0.0.0.0', 5080)
[2023-01-07 12:12:27 +0530] [374560] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:12:27 +0530] [374560] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:27 +0530] [374560] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:28 +0530] [374560] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:28 +0530] [374560] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:29 +0530] [374560] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:12:29 +0530] [374560] [ERROR] Retrying in 1 second.
[2023-01-07 12:12:30 +0530] [374560] [INFO] Listening at: http://0.0.0.0:5080 (374560)
[2023-01-07 12:12:30 +0530] [374560] [INFO] Using worker: sync
[2023-01-07 12:12:30 +0530] [374561] [INFO] Booting worker with pid: 374561
[2023-01-07 12:14:24 +0530] [374789] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:14:24 +0530] [374789] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:24 +0530] [374789] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:25 +0530] [374789] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:25 +0530] [374789] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:26 +0530] [374789] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:26 +0530] [374789] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:27 +0530] [374789] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:27 +0530] [374789] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:28 +0530] [374789] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:28 +0530] [374789] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:29 +0530] [374789] [ERROR] Can't connect to ('0.0.0.0', 5080)
[2023-01-07 12:14:30 +0530] [374797] [INFO] Starting gunicorn 20.1.0
[2023-01-07 12:14:30 +0530] [374797] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:30 +0530] [374797] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:31 +0530] [374797] [ERROR] Connection in use: ('0.0.0.0', 5080)
[2023-01-07 12:14:31 +0530] [374797] [ERROR] Retrying in 1 second.
[2023-01-07 12:14:32 +0530] [374797] [INFO] Listening at: http://0.0.0.0:5080 (374797)
[2023-01-07 12:14:32 +0530] [374797] [INFO] Using worker: sync
[2023-01-07 12:14:32 +0530] [374804] [INFO] Booting worker with pid: 374804
[2023-01-07 12:15:07 +0530] [374797] [INFO] Handling signal: term
[2023-01-07 12:15:07 +0530] [374804] [INFO] Worker exiting (pid: 374804)
[2023-01-07 12:15:08 +0530] [374797] [INFO] Shutting down: Master
[2023-01-07 13:15:02 +0530] [386254] [INFO] Starting gunicorn 20.1.0
[2023-01-07 13:15:02 +0530] [386254] [INFO] Listening at: http://0.0.0.0:5080 (386254)
[2023-01-07 13:15:02 +0530] [386254] [INFO] Using worker: sync
[2023-01-07 13:15:02 +0530] [386261] [INFO] Booting worker with pid: 386261
[2023-01-07 22:23:14 +0530] [421351] [INFO] Starting gunicorn 20.1.0
[2023-01-07 22:23:14 +0530] [421351] [INFO] Listening at: http://0.0.0.0:5080 (421351)
[2023-01-07 22:23:14 +0530] [421351] [INFO] Using worker: sync
[2023-01-07 22:23:14 +0530] [421360] [INFO] Booting worker with pid: 421360
[2023-01-08 12:24:31 +0530] [421351] [INFO] Handling signal: term
[2023-01-08 12:24:31 +0530] [421360] [INFO] Worker exiting (pid: 421360)
[2023-01-08 12:24:31 +0530] [421351] [INFO] Shutting down: Master
[2023-01-08 12:24:34 +0530] [481686] [INFO] Starting gunicorn 20.1.0
[2023-01-08 12:24:34 +0530] [481686] [INFO] Listening at: http://0.0.0.0:5080 (481686)
[2023-01-08 12:24:34 +0530] [481686] [INFO] Using worker: sync
[2023-01-08 12:24:34 +0530] [481696] [INFO] Booting worker with pid: 481696
[2023-01-08 12:28:00 +0530] [481686] [INFO] Handling signal: term
[2023-01-08 12:28:00 +0530] [481696] [INFO] Worker exiting (pid: 481696)
[2023-01-08 12:28:01 +0530] [481686] [INFO] Shutting down: Master
[2023-01-08 12:28:02 +0530] [482318] [INFO] Starting gunicorn 20.1.0
[2023-01-08 12:28:02 +0530] [482318] [INFO] Listening at: http://0.0.0.0:5080 (482318)
[2023-01-08 12:28:02 +0530] [482318] [INFO] Using worker: sync
[2023-01-08 12:28:02 +0530] [482326] [INFO] Booting worker with pid: 482326
[2023-01-08 13:50:48 +0530] [482318] [INFO] Handling signal: term
[2023-01-08 13:50:48 +0530] [482326] [INFO] Worker exiting (pid: 482326)
[2023-01-08 13:50:49 +0530] [482318] [INFO] Shutting down: Master
[2023-01-08 13:50:50 +0530] [493836] [INFO] Starting gunicorn 20.1.0
[2023-01-08 13:50:50 +0530] [493836] [INFO] Listening at: http://0.0.0.0:5080 (493836)
[2023-01-08 13:50:50 +0530] [493836] [INFO] Using worker: sync
[2023-01-08 13:50:50 +0530] [493847] [INFO] Booting worker with pid: 493847
[2023-01-08 13:52:17 +0530] [493836] [INFO] Handling signal: term
[2023-01-08 13:52:17 +0530] [493847] [INFO] Worker exiting (pid: 493847)
[2023-01-08 13:52:18 +0530] [493836] [INFO] Shutting down: Master
[2023-01-08 13:52:19 +0530] [494014] [INFO] Starting gunicorn 20.1.0
[2023-01-08 13:52:19 +0530] [494014] [INFO] Listening at: http://0.0.0.0:5080 (494014)
[2023-01-08 13:52:19 +0530] [494014] [INFO] Using worker: sync
[2023-01-08 13:52:19 +0530] [494023] [INFO] Booting worker with pid: 494023
[2023-01-08 13:52:32 +0530] [494014] [INFO] Handling signal: term
[2023-01-08 13:52:32 +0530] [494023] [INFO] Worker exiting (pid: 494023)
[2023-01-08 13:52:32 +0530] [494014] [INFO] Shutting down: Master
[2023-01-08 13:52:34 +0530] [494077] [INFO] Starting gunicorn 20.1.0
[2023-01-08 13:52:34 +0530] [494077] [INFO] Listening at: http://0.0.0.0:5080 (494077)
[2023-01-08 13:52:34 +0530] [494077] [INFO] Using worker: sync
[2023-01-08 13:52:34 +0530] [494087] [INFO] Booting worker with pid: 494087
[2023-01-08 15:32:13 +0530] [494077] [INFO] Handling signal: term
[2023-01-08 15:32:13 +0530] [494087] [INFO] Worker exiting (pid: 494087)
[2023-01-08 15:32:14 +0530] [494077] [INFO] Shutting down: Master
[2023-01-08 15:32:15 +0530] [500547] [INFO] Starting gunicorn 20.1.0
[2023-01-08 15:32:15 +0530] [500547] [INFO] Listening at: http://0.0.0.0:5080 (500547)
[2023-01-08 15:32:15 +0530] [500547] [INFO] Using worker: sync
[2023-01-08 15:32:15 +0530] [500557] [INFO] Booting worker with pid: 500557
[2023-01-08 15:33:24 +0530] [500547] [INFO] Handling signal: term
[2023-01-08 15:33:24 +0530] [500557] [INFO] Worker exiting (pid: 500557)
[2023-01-08 15:33:24 +0530] [500547] [INFO] Shutting down: Master
[2023-01-08 15:33:26 +0530] [500878] [INFO] Starting gunicorn 20.1.0
[2023-01-08 15:33:26 +0530] [500878] [INFO] Listening at: http://0.0.0.0:5080 (500878)
[2023-01-08 15:33:26 +0530] [500878] [INFO] Using worker: sync
[2023-01-08 15:33:26 +0530] [500888] [INFO] Booting worker with pid: 500888
[2023-01-08 16:22:29 +0530] [500878] [INFO] Handling signal: term
[2023-01-08 16:22:29 +0530] [500888] [INFO] Worker exiting (pid: 500888)
[2023-01-08 16:22:29 +0530] [500878] [INFO] Shutting down: Master
[2023-01-08 16:22:30 +0530] [506066] [INFO] Starting gunicorn 20.1.0
[2023-01-08 16:22:30 +0530] [506066] [INFO] Listening at: http://0.0.0.0:5080 (506066)
[2023-01-08 16:22:30 +0530] [506066] [INFO] Using worker: sync
[2023-01-08 16:22:30 +0530] [506068] [INFO] Booting worker with pid: 506068
[2023-01-08 16:25:23 +0530] [506066] [INFO] Handling signal: term
[2023-01-08 16:25:23 +0530] [506068] [INFO] Worker exiting (pid: 506068)
[2023-01-08 16:25:23 +0530] [506066] [INFO] Shutting down: Master
[2023-01-08 16:25:25 +0530] [506600] [INFO] Starting gunicorn 20.1.0
[2023-01-08 16:25:25 +0530] [506600] [INFO] Listening at: http://0.0.0.0:5080 (506600)
[2023-01-08 16:25:25 +0530] [506600] [INFO] Using worker: sync
[2023-01-08 16:25:25 +0530] [506608] [INFO] Booting worker with pid: 506608
[2023-01-08 16:34:58 +0530] [506600] [INFO] Handling signal: term
[2023-01-08 16:34:58 +0530] [506608] [INFO] Worker exiting (pid: 506608)
[2023-01-08 16:34:58 +0530] [506600] [INFO] Shutting down: Master
[2023-01-08 16:35:00 +0530] [509580] [INFO] Starting gunicorn 20.1.0
[2023-01-08 16:35:00 +0530] [509580] [INFO] Listening at: http://0.0.0.0:5080 (509580)
[2023-01-08 16:35:00 +0530] [509580] [INFO] Using worker: sync
[2023-01-08 16:35:00 +0530] [509599] [INFO] Booting worker with pid: 509599
[2023-01-08 16:37:08 +0530] [509580] [INFO] Handling signal: term
[2023-01-08 16:37:08 +0530] [509599] [INFO] Worker exiting (pid: 509599)
[2023-01-08 16:37:08 +0530] [509580] [INFO] Shutting down: Master
[2023-01-08 16:37:27 +0530] [510030] [INFO] Starting gunicorn 20.1.0
[2023-01-08 16:37:27 +0530] [510030] [INFO] Listening at: http://0.0.0.0:5080 (510030)
[2023-01-08 16:37:27 +0530] [510030] [INFO] Using worker: sync
[2023-01-08 16:37:27 +0530] [510043] [INFO] Booting worker with pid: 510043
